### ISSUE TITLE
JSONata for Python seems broken

### ISSUE THREAD

**Issue by anshikg** [qlyoung/pyjsonata#1]
Hi,
I am trying to use JSONata for python by using the python wrapper available here: https://pypi.org/project/pyjsonata/ I can't seem to install this, pip install command fails with:

```
 pip install pyjsonata                                       
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pyjsonata (from versions: none)
ERROR: No matching distribution found for pyjsonata
```

Is there a plan to fix the PyPI build? I see that the make file needs to be written in python as mentioned here:
```
Source packages are currently broken until I can be bothered to rewrite jsonata-c’s Makefile in Python, as required by setuptools.
```

I am planning to take a dependency on JSONata in python and java and was hoping to understand if this is available for customer use. Any help here would be greatly appreciated.

Thanks

**Comment by qlyoung** [comment]
There's now a pure python implementation that I would recommend using instead of this project:
https://github.com/rayokota/jsonata-python
