### ISSUE TITLE
Publish builds for Python 3.10

### ISSUE THREAD

**Issue by svet-b** [qlyoung/pyjsonata#2]
At the moment installation on the most recent Python version is not possible, since published builds on PyPi only exist up to 3.9. As you mention in the README, the builds should in principle be compatible (or be made compatible by changing the Python version to `none`). But for the time being - for anyone who isn't looking to fork this, build it themselves, and set up a custom install mechanism - simply running `pip install pyjsonata` unfortunately fails with `No matching distribution found`.

**Comment by dakhnod** [comment]
A possible workaround for this is `pip install git+https://github.com/qlyoung/pyjsonata.git` to install directly from the git repository.

**Comment by bhavaniravi** [comment]
The pip install works with git but when I try the same with poetry, it gives an error

```
 Failed to clone https://github.com/qlyoung/jsonata-c.git at '182f3e108bf00ff03471c2033b1ae53fda2c20d4', verify ref exists on remote.
```

**Comment by qlyoung** [comment]
There is now a pure python implementation available, please give this a try:
https://github.com/rayokota/jsonata-python
