### ISSUE TITLE
Building on macOS 13.6 fails with '-std=c++14' not allowed with 'C'

### ISSUE THREAD

**Issue by svenXY** [qlyoung/pyjsonata#4]
`
python -m pip install jsonata

Collecting jsonata
  Using cached jsonata-0.2.4.tar.gz (963 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: jsonata
  Building wheel for jsonata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for jsonata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-7al9bvlz/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'readme'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13.3-arm64-cpython-311
      creating build/lib.macosx-13.3-arm64-cpython-311/jsonata
      copying jsonata/__init__.py -> build/lib.macosx-13.3-arm64-cpython-311/jsonata
      running build_ext
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/Sven/jsonata/.venv/include -I/Users/Sven/.pyenv/versions/3.11.2/include/python3.11 -c flagcheck.cpp -o flagcheck.o -std=c++17
      building '_jsonata' extension
      creating build/temp.macosx-13.3-arm64-cpython-311
      creating build/temp.macosx-13.3-arm64-cpython-311/duktape-2.7.0
      creating build/temp.macosx-13.3-arm64-cpython-311/duktape-2.7.0/src
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -DVERSION_INFO=0.2.4 -I/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-7al9bvlz/overlay/lib/python3.11/site-packages/pybind11/include -Iduktape-2.7.0/src/ -I/Users/Sven/jsonata/.venv/include -I/Users/Sven/.pyenv/versions/3.11.2/include/python3.11 -c duktape-2.7.0/src/duktape.c -o build/temp.macosx-13.3-arm64-cpython-311/duktape-2.7.0/src/duktape.o -std=c++17 -mmacosx-version-min=10.14 -fvisibility=hidden -g0 -std=c++14
      error: invalid argument '-std=c++14' not allowed with 'C'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jsonata
Failed to build jsonata
ERROR: Could not build wheels for jsonata, which is required to install pyproject.toml-based projects

`

**Comment by qlyoung** [comment]
I'll take a look if I can find the time, updating this package has been on my to-do list for ages.

**Comment by qlyoung** [comment]
Don't have time to fix this. Recommend using this instead:
https://github.com/rayokota/jsonata-python
